version: '2'

services:
  # Primary services
  app:
    env_file:
      - .env
    depends_on:
      - cache
      - db

  # Upstream services
  cache:
    image: memcached:1.4-alpine

  db:
    image: mysql:5.7
    env_file:
      - .env
