version: '2'

services:
  # Primary services
  app:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  # Upstream services
  db:
    volumes:
      - .data/db:/var/lib/mysql
