version: '2'

services:
  # Primary services
  web:
    depends_on:
      - db

  # Upstream services
  cache:
    image: memcached:1.4-alpine

  db:
    image: mysql:5.7
    env_file:
      - ./db.env
