version: '2'

services:
  # Primary services
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ${VAR_VOLUME}:/usr/local/var
      - ${SSL_VOLUME}:/etc/ssl
      - ${STATIC_VOLUME}:/staticfiles
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  # Upstream services
  app:
    command: bin/app-entry-point.sh
    volumes:
      - ${VAR_VOLUME}:/usr/local/var
      - ${STATIC_VOLUME}:/app/staticfiles

  db:
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
