version: '2'

services:
  # Primary services
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - ${SHARED_VOLUME}:/shared
      - ${SSL_VOLUME}:/etc/ssl
      - ${STATIC_VOLUME}:/staticfiles
    ports:
      - "80:80"
      - "443:443"

  # Upstream services
  app:
    build: .
    command: bin/app-entry-point.sh
    volumes:
      - ${SHARED_VOLUME}:/shared
      - ${STATIC_VOLUME}:/app/staticfiles

  db:
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
